// <auto-generated />
using System;
using EntityFrameworkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.Data.Migrations
{
    [DbContext(typeof(FootballLeageDbContext))]
    [Migration("20250303233805_SeededTeams")]
    partial class SeededTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Domain.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            CreateDate = new DateTime(2025, 3, 3, 23, 38, 5, 295, DateTimeKind.Unspecified).AddTicks(3313),
                            Name = "Real Madrid F.C"
                        },
                        new
                        {
                            TeamId = 2,
                            CreateDate = new DateTime(2025, 3, 3, 23, 38, 5, 295, DateTimeKind.Unspecified).AddTicks(3610),
                            Name = "Tivoli Gardens F.C"
                        },
                        new
                        {
                            TeamId = 3,
                            CreateDate = new DateTime(2025, 3, 3, 23, 38, 5, 295, DateTimeKind.Unspecified).AddTicks(3613),
                            Name = "Waterhouse F.C"
                        },
                        new
                        {
                            TeamId = 4,
                            CreateDate = new DateTime(2025, 3, 3, 23, 38, 5, 295, DateTimeKind.Unspecified).AddTicks(3614),
                            Name = "Humble Lions F.C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
